### ISSUE TITLE
Joystick

### ISSUE THREAD

**Issue by ferhatm** [itu-rover/Rover_Web_Gui#7]
Joystick kontrolü ve publishi

**Comment by hgaren** [comment]
18.01.2018​
 rover_18.tar.gz
<https://drive.google.com/file/d/1E9yWHjEHIWYZlhlcxIMpCjdSfOeh-dOa/view?usp=drive_web>
​

2018-01-17 17:53 GMT+03:00 tahameg <notifications@github.com>:
